apiVersion: 1
contactPoints:
  - orgId: 1
    name: AKS-Failure-Email-Alerts
    receivers:
      - uid: email-receiver
        type: email
        settings:
          addresses: "<your-email@example.com>"
          singleEmail: false
        disableResolveMessage: false
