apiVersion: 1
policies:
  - orgId: 1
    receiver: AKS-Failure-Email-Alerts
    group_by:
      - grafana_folder
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: AKS-Failure-Email-Alerts
        matchers:
          - scenario =~ "crashloop|oom|imagepull|pending|liveness"
        continue: false
