apiVersion: v1
kind: Pod
metadata:
  name: crashloop-demo
  namespace: default
  labels:
    app: failure-simulation
    scenario: crashloop
spec:
  containers:
  - name: crashloop-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args: 
      - echo "Application starting...";
        sleep 5;
        echo "Simulating crash!";
        exit 1
  restartPolicy: Always
